#!/usr/bin/env node
/**
 * Integration Tests: F014 Team Management
 * Auto-generated by sprint pipeline
 */

import { createClient } from "@supabase/supabase-js";

// === CONFIG ===
const SUPABASE_URL = "https://yihypotpywllwoymjduz.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpaHlwb3RweXdsbHdveW1qZHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4NTM4NzUsImV4cCI6MjA4NDQyOTg3NX0.VGvocHahZb6kgUzZs5S1RZ8jgq9KWPb42qKVQ8Fqqs4";

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// === TEST HELPERS ===
let passed = 0, failed = 0;

async function test(name, fn) {
  try {
    await fn();
    console.log(`✅ ${name}`);
    passed++;
  } catch (e) {
    console.log(`❌ ${name}: ${e.message}`);
    failed++;
  }
}

function assert(cond, msg) {
  if (!cond) throw new Error(msg);
}

// === TESTS ===
console.log("🧪 Running F014 Team Management integration tests...\n");

// Test 1: RPC list_org_members exists
await test("RPC list_org_members exists", async () => {
  const { error } = await supabase.rpc("list_org_members", {
    _org_id: "00000000-0000-0000-0000-000000000000"
  });
  if (error?.message?.includes("does not exist")) throw error;
});

// Test 2: RPC invite_org_member exists
await test("RPC invite_org_member exists", async () => {
  const { error } = await supabase.rpc("invite_org_member", {
    _org_id: "00000000-0000-0000-0000-000000000000",
    _email: "test@test.com",
    _role: "support"
  });
  if (error?.message?.includes("does not exist")) throw error;
});

// Test 3: RPC update_member_role exists
await test("RPC update_member_role exists", async () => {
  const { error } = await supabase.rpc("update_member_role", {
    _member_id: "00000000-0000-0000-0000-000000000000",
    _new_role: "admin"
  });
  if (error?.message?.includes("does not exist")) throw error;
});

// Test 4: RPC remove_org_member exists
await test("RPC remove_org_member exists", async () => {
  const { error } = await supabase.rpc("remove_org_member", {
    _member_id: "00000000-0000-0000-0000-000000000000"
  });
  if (error?.message?.includes("does not exist")) throw error;
});

// Test 5: RPC get_current_user_role exists
await test("RPC get_current_user_role exists", async () => {
  const { error } = await supabase.rpc("get_current_user_role", {
    _org_id: "00000000-0000-0000-0000-000000000000"
  });
  if (error?.message?.includes("does not exist")) throw error;
});

// Test 6: invite_org_member returns UNAUTHORIZED without auth
await test("invite_org_member returns UNAUTHORIZED without auth", async () => {
  const { data } = await supabase.rpc("invite_org_member", {
    _org_id: "00000000-0000-0000-0000-000000000000",
    _email: "test@test.com",
    _role: "support"
  });
  assert(data?.error === "UNAUTHORIZED", `Expected UNAUTHORIZED, got ${data?.error}`);
});

// Test 7: update_member_role returns NOT_FOUND for invalid member
await test("update_member_role returns NOT_FOUND for invalid member", async () => {
  const { data } = await supabase.rpc("update_member_role", {
    _member_id: "00000000-0000-0000-0000-000000000000",
    _new_role: "admin"
  });
  assert(data?.error === "NOT_FOUND", `Expected NOT_FOUND, got ${data?.error}`);
});

// Test 8: remove_org_member returns NOT_FOUND for invalid member
await test("remove_org_member returns NOT_FOUND for invalid member", async () => {
  const { data } = await supabase.rpc("remove_org_member", {
    _member_id: "00000000-0000-0000-0000-000000000000"
  });
  assert(data?.error === "NOT_FOUND", `Expected NOT_FOUND, got ${data?.error}`);
});

// Test 9: org_members table accessible
await test("org_members table exists", async () => {
  const { error } = await supabase
    .from("org_members")
    .select("id")
    .limit(1);
  if (error?.code === "42P01") throw new Error("Table does not exist");
});

// Test 10: list_org_members returns empty for non-member
await test("list_org_members returns empty for non-member", async () => {
  const { data } = await supabase.rpc("list_org_members", {
    _org_id: "00000000-0000-0000-0000-000000000000"
  });
  assert(Array.isArray(data) && data.length === 0, "Should return empty array");
});

// === SUMMARY ===
console.log(`\n${"=".repeat(40)}`);
console.log(`✅ Passed: ${passed} | ❌ Failed: ${failed}`);
process.exit(failed > 0 ? 1 : 0);
