#!/usr/bin/env node
/**
 * Integration Tests: F013 Invitation System
 * Auto-generated by sprint pipeline
 */

import { createClient } from "@supabase/supabase-js";

// === CONFIG ===
const SUPABASE_URL = "https://yihypotpywllwoymjduz.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpaHlwb3RweXdsbHdveW1qZHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4NTM4NzUsImV4cCI6MjA4NDQyOTg3NX0.VGvocHahZb6kgUzZs5S1RZ8jgq9KWPb42qKVQ8Fqqs4";

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// === TEST HELPERS ===
let passed = 0, failed = 0;

async function test(name, fn) {
  try {
    await fn();
    console.log(`✅ ${name}`);
    passed++;
  } catch (e) {
    console.log(`❌ ${name}: ${e.message}`);
    failed++;
  }
}

function assert(cond, msg) {
  if (!cond) throw new Error(msg);
}

// === TESTS ===
console.log("🧪 Running F013 Invitation System integration tests...\n");

// Test 1: RPC generate_invitation_code exists
await test("RPC generate_invitation_code exists", async () => {
  const { error } = await supabase.rpc("generate_invitation_code", {
    _org_id: "00000000-0000-0000-0000-000000000000"
  });
  // Should fail with UNAUTHORIZED (not "does not exist")
  if (error?.message?.includes("does not exist")) throw error;
});

// Test 2: RPC validate_invitation_code exists
await test("RPC validate_invitation_code exists", async () => {
  const { data, error } = await supabase.rpc("validate_invitation_code", {
    _code: "TESTCODE"
  });
  if (error?.message?.includes("does not exist")) throw error;
  // Should return {valid: false} for non-existent code
  assert(data?.valid === false, "Should return valid: false");
});

// Test 3: Validation returns CODE_NOT_FOUND for invalid code
await test("Validation returns CODE_NOT_FOUND for invalid code", async () => {
  const { data } = await supabase.rpc("validate_invitation_code", {
    _code: "INVALID123"
  });
  assert(data?.error === "CODE_NOT_FOUND", `Expected CODE_NOT_FOUND, got ${data?.error}`);
});

// Test 4: RPC redeem_invitation_code exists
await test("RPC redeem_invitation_code exists", async () => {
  const { data, error } = await supabase.rpc("redeem_invitation_code", {
    _code: "TESTCODE"
  });
  if (error?.message?.includes("does not exist")) throw error;
  // Should return valid: false for non-existent code
  assert(data?.valid === false || data?.error, "Should return error for invalid code");
});

// Test 5: RPC get_invitation_stats exists
await test("RPC get_invitation_stats exists", async () => {
  const { error } = await supabase.rpc("get_invitation_stats", {
    _org_id: "00000000-0000-0000-0000-000000000000"
  });
  if (error?.message?.includes("does not exist")) throw error;
});

// Test 6: RPC deactivate_invitation_code exists
await test("RPC deactivate_invitation_code exists", async () => {
  const { error } = await supabase.rpc("deactivate_invitation_code", {
    _code_id: "00000000-0000-0000-0000-000000000000"
  });
  if (error?.message?.includes("does not exist")) throw error;
});

// Test 7: invitation_codes table exists
await test("invitation_codes table exists", async () => {
  const { error } = await supabase
    .from("invitation_codes")
    .select("id")
    .limit(1);
  if (error?.code === "42P01") throw new Error("Table does not exist");
});

// Test 8: invitation_redemptions table exists
await test("invitation_redemptions table exists", async () => {
  const { error } = await supabase
    .from("invitation_redemptions")
    .select("id")
    .limit(1);
  if (error?.code === "42P01") throw new Error("Table does not exist");
});

// Test 9: Generate requires authentication
await test("Generate requires authentication (returns UNAUTHORIZED)", async () => {
  const { data } = await supabase.rpc("generate_invitation_code", {
    _org_id: "00000000-0000-0000-0000-000000000000"
  });
  assert(data?.error === "UNAUTHORIZED", `Expected UNAUTHORIZED, got ${data?.error}`);
});

// Test 10: Stats requires authentication
await test("Stats requires authentication (returns UNAUTHORIZED)", async () => {
  const { data } = await supabase.rpc("get_invitation_stats", {
    _org_id: "00000000-0000-0000-0000-000000000000"
  });
  assert(data?.error === "UNAUTHORIZED", `Expected UNAUTHORIZED, got ${data?.error}`);
});

// === SUMMARY ===
console.log(`\n${"=".repeat(40)}`);
console.log(`✅ Passed: ${passed} | ❌ Failed: ${failed}`);
process.exit(failed > 0 ? 1 : 0);
